# Generated by Django 5.0.6 on 2024-06-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='post_images/'),
        ),
        migrations.DeleteModel(
            name='PostSection',
        ),
    ]
